### ISSUE TITLE
Unable to download several mods with wabbajack

### ISSUE THREAD

**Issue by HolgerFe** [wabbajack-tools/mod-lists#510]
When trying to update the mod via wabbajack, at least 3 mods couldn't be downloaded:
9501,64 - Unable to download Even Better Mod Descriptions - GOTY (Main Version) V.3.2-36105-3-2-1560312979.zip
9501,64 - Unable to download Unofficial Fallout 4 Patch-4598-2-1-1-1586572993.7z
9501,64 - Unable to download VAFS Redux-36519-1-3-1-1565016886.zip
9501,64 - Cannot continue, was unable to download one or more archives
9501,65 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\agent\_work\1\s\Wabbajack.Lib\AInstaller.cs:line 69
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\agent\_work\1\s\Wabbajack.Lib\MO2Installer.cs:line 129
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__46_0() in C:\agent\_work\1\s\Wabbajack.Lib\ABatchProcessor.cs:line 164
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\agent\_work\1\s\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 165
--- End of stack trace from previous location where exception was thrown ---
   at Wabbajack.MO2InstallerVM.Install() in C:\agent\_work\1\s\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 159
   at Wabbajack.InstallerVM.<>c__DisplayClass92_0.<<-ctor>b__69>d.MoveNext() in C:\agent\_work\1\s\Wabbajack\View Models\Installers\InstallerVM.cs:line 364

The "Even Better Mod Descriptions - GOTY" Mod was updated to 3.5 and the older version 3.2 isn't available anymore.
"VAFS Redux - Bullet Time and Manual Critical" and "Unofficial Fallout 4 Patch" were also updated lately.

**Comment by Timboman** [comment]
Not an Issue.
The list file just needs to be recompiled by the Modlist Developer.
