### ISSUE TITLE
Skyrim Particle Patch - Incorrect Hash

### ISSUE THREAD

**Issue by ZujinD** [wabbajack-tools/mod-lists#837]
The Particle Patch is preventing successful installation due to an incorrect hash

141.27 - Downloading Skyrim_Particle_Patch_for_ENB-SSE.zip
146.99 - Hashed download is incorrect
147.8 - Trying to find solution to broken download for Skyrim_Particle_Patch_for_ENB-SSE.zip
147.8 - Looking for generic upgrade for sY23OjXvUnA= (8093794492235615665)
148.62 - No solution for broken download Skyrim_Particle_Patch_for_ENB-SSE.zip GoogleDriveDownloader+State|12tL3_kpm_KXlQvQqEnK3zOAl-sm_H3Fw could be found
148.62 - Hashing Remaining Archives
148.62 - Looking for files to hash
148.64 - Found 675 files to hash
148.75 - Unable to download Skyrim_Particle_Patch_for_ENB-SSE.zip (GoogleDriveDownloader+State|12tL3_kpm_KXlQvQqEnK3zOAl-sm_H3Fw)
148.75 - Cannot continue, was unable to download one or more archives
148.75 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in c:\agent\_work\2\s\Wabbajack.Lib\AInstaller.cs:line 71
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in c:\agent\_work\2\s\Wabbajack.Lib\MO2Installer.cs:line 138
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__46_0() in c:\agent\_work\2\s\Wabbajack.Lib\ABatchProcessor.cs:line 168
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in c:\agent\_work\2\s\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 168
--- End of stack trace from previous location where exception was thrown ---
   at Wabbajack.MO2InstallerVM.Install() in c:\agent\_work\2\s\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 162
   at Wabbajack.InstallerVM.<>c__DisplayClass92_0.<<-ctor>b__69>d.MoveNext() in c:\agent\_work\2\s\Wabbajack\View Models\Installers\InstallerVM.cs:line 367
603.98 - Loading ModLists from GitHub

**Comment by xSkyrimxPlayerx** [comment]
i'm getting the same error when installing :(

**Comment by ixanza** [comment]
This issue is modlist specific not wabbajack specific. Please list what list you’re using and/or check the specific modlist’s channel on discord

**Comment by ZujinD** [comment]
Sorry about that, this issue arises when trying to install The Phoenix Flavour
